export const JS_VERSIONS = [ 1.0, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9 ];

export const RATIOS = {
  '1.33': '4:3',
  '1.78': '16:9',
  '1.6':  '16:10',
  '1.25': '5:4',
  '1.37': '(Academy ratio)',
  '1.43': '(IMAX format)',
  '1.5':  '3:2',
  '1.56': '14:9',
  '1.66': '(Super16 format)',
  '1.85': '(35mm standard)',
  '2.2':  '(70mm standard)',
  '2.35': '(35mm anamorphic pre-1970)',
  '2.39': '(35mm anamorphic post-1970)'
};

export const NAVIGATOR_OPTIONS = [
  'userAgent',
  'appVersion',
  'appName',
  'appCodeName',
  'appMinorVersion',
  'product',
  'productSub',
  'vendor',
  'vendorSub',
  'buildID',
  'platform',
  'cpuClass',
  'oscpu',
  'hardwareConcurrency',
  'maxTouchPoints',
  'browserLanguage',
  'userLanguage',
  'systemLanguage',
  'onLine',
  'doNotTrack',
  'msDoNotTrack',
  'geolocation',
  'cookieEnabled'
];

export const PERFOMANCE_TIMING_OPTIONS = [
  'navigationStart',
  'redirectStart',
  'redirectEnd',
  'fetchStart',
  'domainLookupStart',
  'domainLookupEnd',
  'connectStart',
  'secureConnectionStart',
  'connectEnd',
  'requestStart',
  'responseStart',
  'responseEnd',
  'domLoading',
  'domInteractive',
  'domContentLoadedEventStart',
  'domContentLoadedEventEnd',
  'domComplete',
  'loadEventStart',
  'loadEventEnd',
  'msFirstPaint',
  'unloadEventStart',
  'unloadEventEnd'
];

export const FONT_ARRAY = [
  'Abadi MT Condensed Light',
  'Adobe Fangsong Std',
  'Adobe Hebrew',
  'Adobe Ming Std',
  'Agency FB',
  'Aharoni',
  'Andalus',
  'Angsana New',
  'AngsanaUPC',
  'Aparajita',
  'Arab',
  'Arabic Transparent',
  'Arabic Typesetting',
  'Arial Baltic',
  'Arial Black',
  'Arial CE',
  'Arial CYR',
  'Arial Greek',
  'Arial TUR',
  'Arial',
  'Batang',
  'BatangChe',
  'Bauhaus 93',
  'Bell MT',
  'Bitstream Vera Serif',
  'Bodoni MT',
  'Bookman Old Style',
  'Braggadocio',
  'Broadway',
  'Browallia New',
  'BrowalliaUPC',
  'Calibri Light',
  'Calibri',
  'Californian FB',
  'Cambria Math',
  'Cambria',
  'Candara',
  'Castellar',
  'Casual',
  'Centaur',
  'Century Gothic',
  'Chalkduster',
  'Colonna MT',
  'Comic Sans MS',
  'Consolas',
  'Constantia',
  'Copperplate Gothic Light',
  'Corbel',
  'Cordia New',
  'CordiaUPC',
  'Courier New Baltic',
  'Courier New CE',
  'Courier New CYR',
  'Courier New Greek',
  'Courier New TUR',
  'Courier New',
  'DFKai-SB',
  'DaunPenh',
  'David',
  'DejaVu LGC Sans Mono',
  'Desdemona',
  'DilleniaUPC',
  'DokChampa',
  'Dotum',
  'DotumChe',
  'Ebrima',
  'Engravers MT',
  'Eras Bold ITC',
  'Estrangelo Edessa',
  'EucrosiaUPC',
  'Euphemia',
  'Eurostile',
  'FangSong',
  'Forte',
  'FrankRuehl',
  'Franklin Gothic Heavy',
  'Franklin Gothic Medium',
  'FreesiaUPC',
  'French Script MT',
  'Gabriola',
  'Gautami',
  'Georgia',
  'Gigi',
  'Gisha',
  'Goudy Old Style',
  'Gulim',
  'GulimChe',
  'GungSeo',
  'Gungsuh',
  'GungsuhChe',
  'Haettenschweiler',
  'Harrington',
  'Hei S',
  'HeiT',
  'Heisei Kaku Gothic',
  'Hiragino Sans GB',
  'Impact',
  'Informal Roman',
  'IrisUPC',
  'Iskoola Pota',
  'JasmineUPC',
  'KacstOne',
  'KaiTi',
  'Kalinga',
  'Kartika',
  'Khmer UI',
  'Kino MT',
  'KodchiangUPC',
  'Kokila',
  'Kozuka Gothic Pr6N',
  'Lao UI',
  'Latha',
  'Leelawadee',
  'Levenim MT',
  'LilyUPC',
  'Lohit Gujarati',
  'Loma',
  'Lucida Bright',
  'Lucida Console',
  'Lucida Fax',
  'Lucida Sans Unicode',
  'MS Gothic',
  'MS Mincho',
  'MS PGothic',
  'MS PMincho',
  'MS Reference Sans Serif',
  'MS UI Gothic',
  'MV Boli',
  'Magneto',
  'Malgun Gothic',
  'Mangal',
  'Marlett',
  'Matura MT Script Capitals',
  'Meiryo UI',
  'Meiryo',
  'Menlo',
  'Microsoft Himalaya',
  'Microsoft JhengHei',
  'Microsoft New Tai Lue',
  'Microsoft PhagsPa',
  'Microsoft Sans Serif',
  'Microsoft Tai Le',
  'Microsoft Uighur',
  'Microsoft YaHei',
  'Microsoft Yi Baiti',
  'MingLiU',
  'MingLiU-ExtB',
  'MingLiU_HKSCS',
  'MingLiU_HKSCS-ExtB',
  'Miriam Fixed',
  'Miriam',
  'Mongolian Baiti',
  'MoolBoran',
  'NSimSun',
  'Narkisim',
  'News Gothic MT',
  'Niagara Solid',
  'Nyala',
  'PMingLiU',
  'PMingLiU-ExtB',
  'Palace Script MT',
  'Palatino Linotype',
  'Papyrus',
  'Perpetua',
  'Plantagenet Cherokee',
  'Playbill',
  'Prelude Bold',
  'Prelude Condensed Bold',
  'Prelude Condensed Medium',
  'Prelude Medium',
  'PreludeCompressedWGL Black',
  'PreludeCompressedWGL Bold',
  'PreludeCompressedWGL Light',
  'PreludeCompressedWGL Medium',
  'PreludeCondensedWGL Black',
  'PreludeCondensedWGL Bold',
  'PreludeCondensedWGL Light',
  'PreludeCondensedWGL Medium',
  'PreludeWGL Black',
  'PreludeWGL Bold',
  'PreludeWGL Light',
  'PreludeWGL Medium',
  'Raavi',
  'Rachana',
  'Rockwell',
  'Rod',
  'Sakkal Majalla',
  'Sawasdee',
  'Script MT Bold',
  'Segoe Print',
  'Segoe Script',
  'Segoe UI Light',
  'Segoe UI Semibold',
  'Segoe UI Symbol',
  'Segoe UI',
  'Shonar Bangla',
  'Showcard Gothic',
  'Shruti',
  'SimHei',
  'SimSun',
  'SimSun-ExtB',
  'Simplified Arabic Fixed',
  'Simplified Arabic',
  'Snap ITC',
  'Sylfaen',
  'Symbol',
  'Tahoma',
  'Times New Roman Baltic',
  'Times New Roman CE',
  'Times New Roman CYR',
  'Times New Roman Greek',
  'Times New Roman TUR',
  'Times New Roman',
  'TlwgMono',
  'Traditional Arabic',
  'Trebuchet MS',
  'Tunga',
  'Tw Cen MT Condensed Extra Bold',
  'Ubuntu',
  'Umpush',
  'Univers',
  'Utopia',
  'Utsaah',
  'Vani',
  'Verdana',
  'Vijaya',
  'Vladimir Script',
  'Vrinda',
  'Webdings',
  'Wide Latin',
  'Wingdings'
];